### ISSUE TITLE
More detailed documentation; CSS styling 

### ISSUE THREAD

**Issue by VasilijeBursac** [UnevenSoftware/vue-insta-stories#3]
Hello guys,

I really like your Insta Stories component, but I can't make it look like it looks in your demo (https://unevensoftware.github.io/vue-insta-stories/).

I tried to read the documentation, but it doesn't have a lot of details... Especially part where style for full screen or in page needs to be done, it doesn't seem to work for me...

Can you, please, at least provide the code for your demo example, just so we can see how to set certain things to look like they do in that live demo?

Best regards! 😄

**Comment by dnldsht** [comment]
The demo use tailwind for the styling, and with those classes (`absolute top-0 h-fill w-100vw md:(h-730px w-420px relative)`) you can make it work like the demo, if you are not familiar with tailwind it generates this css:
```css
.ig-stories {
  position: absolute;
  height: 100vh;
  height: -webkit-fill-available;
  width: 100vw;
  top: 0;
}

@media (min-width: 768px) {
  .ig-stories {
    position: relative;
    height: 730px;
    width: 420px;
  }
}
```

Yeah you are right docs are terrible.
